apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: osac-ui
  namespace: osac
  labels:
    app: osac-ui
spec:
  host: osac-console.apps.osac.service.demo
  to:
    kind: Service
    name: osac-ui
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
